FROM eclipse-temurin:17-jdk-alpine
COPY ../../target/springapplicationforcloud-0.0.1-SNAPSHOT.jar springapplicationforcloud-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/springapplicationforcloud-0.0.1-SNAPSHOT.jar"]